name: Generate Stats Badge 🎖️

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily
  workflow_dispatch:  # Manual trigger option

jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Stats
        uses: cicirello/contribution-stats-action@v2
        with:
          token: ${}
          outputPath: "./docs/badge.md"  # Save badge here

      - name: Commit Badge
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Stats Badge 🏅"
          file_pattern: "./docs/badge.md"
